name: weightlog
description: "Set a goal and track your weight day by day"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.4+9

environment:
    sdk: ">=3.3.0 <4.0.0"
    flutter: 3.35.1

dependencies:
    flutter:
        sdk: flutter
    uuid: ^4.3.3
    intl: ^0.20.0
    flutter_riverpod: ^2.4.10
    sqflite: ^2.3.2
    path: ^1.9.0
    path_provider: ^2.1.2
    shared_preferences: ^2.2.2
    fl_chart: ^1.0.0
    file_picker: ^10.1.9

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0
flutter:
    uses-material-design: true

